import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { GetServerSideProps } from "next";
import getBlogs from "../server/blogs";

const inter = Inter({ subsets: ["latin"] });

export default function Home({blogs} : any) {
  console.log(blogs)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ()=>{
  let blogs = await getBlogs()
  console.log(blogs)
  return {
    props:{
      blogs
    }
  }
}
